version: '3.1'

services:
  web:
    image: micro-example:latest
    restart: always
    ports:
      - 8080:8080

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    volumes:
      - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true

  chronograf:
    image: chronograf:1.5
    ports:
      - 8888:8888
    links:
      - influxdb

  telegraf:
    image: telegraf:1.7
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    links:
      - influxdb

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    links:
      - telegraf